### ISSUE TITLE
how to build the current 1.4 branch

### ISSUE THREAD

**Issue by MunchyG** [blushiemagic/MagicStorage#122]
I just get and error with recursive crafting when I try to build it.

**Comment by BryanAldrich** [comment]
I got the 1.4 branch of recursive craft, used the develop mods button in game to build recursivecraft, then this one. both build, but, this mod doesn't load.

**Comment by absoluteAquarian** [comment]
I have not tested nor built the 1.4 branch, so I can't guarantee that it would even build
