### ISSUE TITLE
[1.4 alpha] Items are missing in multiplayer

### ISSUE THREAD

**Issue by Domaman202** [blushiemagic/MagicStorage#143]
When you take items in multiplayer mode, they disappear into nowhere

**Comment by ExterminatorX99** [comment]
What version of MS are you using?

**Comment by Domaman202** [comment]
last

**Comment by Domaman202** [comment]
0.5.1.2

**Comment by ExterminatorX99** [comment]
The latest workshop version has issues.
He author is currently busy so he can't update it, but there's a fix in the
Magic Storage discord.
https://discord.gg/FemPG7eev4

**Comment by Domaman202** [comment]
ok thx
