### ISSUE TITLE
Storage crafting terminal recipe bug

### ISSUE THREAD

**Issue by Eriffe** [blushiemagic/MagicStorage#17]
crafting terminal only show recipes from items in player inventory... i have resouces in storage, but if i have only in storage the recipe not work. but if have in player inventory i can craft, still use resource from storage but i need all items in my inventory too.

**Comment by bluemagic123** [comment]
Hmm, that is odd. What other mods are you using?

**Comment by Eriffe** [comment]
"BossChecklist",
  "ExperienceAndClasses",
  "ItemChecklist",
  "MagicStorage",
  "imkSushisMod",
  "SimpleAutoChests",
  "SummonersAssociation",
  "imkSushisNaturallyOccuringMoonsMod",
  "Project_Logic",
  "AllTheWalls",
  "HamstarHelpers",
  "Wormholes",
  "WorldGenPreviewer",
  "AutoTrash",
  "WheresMyItems",
  "MoreAccessories",
  "FastStart",
  "ZM",
  "ShorterRespawn",
  "Expeditions",
  "ExpeditionsContent",
  "Tremor",
  "QLS_Updated",
  "CheatSheet",
  "WhatAmmoDoesItShoot",
  "Luiafk",
  "Fargowiltas",
  "RecipeBrowser",
  "FrecMod",
  "ReforgeArmor",
  "CompactUI",
  "FlyingMinionsIgnoreTerrain",
  "YoyoAttackSpeedWorkaround",
  "CalamityMod",
  "LargeWorldEnabler",
  "CosmeticVariety",
  "HEROsMod"

all up to date

**Comment by bluemagic123** [comment]
Hmm, could you try to make a test world and player and see if this bug happens with only Magic Storage and Cheat Sheet enabled? If it works properly, then reenable the mods one by one until the problem happens again.

**Comment by Eriffe** [comment]
now work. only reinstall Magic Storage...

**Comment by slippycheeze** [comment]
Note: this update fixes the translation bug for me, without changing anything else.  Thanks!
