### ISSUE TITLE
Useless item and uncomfortable system

### ISSUE THREAD

**Issue by JustJesus** [blushiemagic/MagicStorage#188]
![Screenshot_22](https://user-images.githubusercontent.com/82801093/177310307-6497b424-0cd8-487b-85a4-5602141e183b.png)
![Screenshot_23](https://user-images.githubusercontent.com/82801093/177310312-2cb09a3c-eb46-4ac0-b051-de356772b6f3.png)

I did not find any information about the "environment access" item and I do not know what it is for, what I need help with.
It is also very inconvenient that you can not make items from the resources that I have in my inventory.
There is also a bug where items from cells disappear when connection blocks are removed nearby, but then everything returns back.

**Comment by ExterminatorX99** [comment]
> I did not find any information about the "environment access" item and I do not know what it is for, what I need help with.

Next update adds tooltips and explanation. I believe the Automaton npc has some info about it right now.

> It is also very inconvenient that you can not make items from the resources that I have in my inventory.

In consideration if it is to be allowed. Maybe as a separate component?

> There is also a bug where items from cells disappear when connection blocks are removed nearby, but then everything returns back.

Known bug. Fixed in next update

**Comment by JustJesus** [comment]
> Next update adds tooltips and explanation. I believe the Automaton npc has some info about it right now.

 NPC hasn't

>In consideration if it is to be allowed. Maybe as a separate component?

Mb
