### ISSUE TITLE
[Multiplayer] Massive lags when crafting

### ISSUE THREAD

**Issue by Yianen** [blushiemagic/MagicStorage#19]
As the title says, we often have some issues when crafting something continuously through the crafting interface (eg. lots of arrows or bullets, etc). Usually the one crafting gets less lags, but the other connected players can barely move (one of my friend basically cannot move at all). 

Some info to clarify:
- We are playing on local network w/ Steam.
- We have 5 storage boxes, approx. 500/600 items in it atm. 
- The problem first arose relatively early in the game, before wall of flesh was killed (relatively low amount of resources, less lag as well)
- The game runs constantly on 50% of CPU (intel i5 4690, 3.5Ghz 4 cores) when this map (with magic storage) launched on multiplayer, 18% when launched assingle player. Furthermore, a map with no magic storage on multiplayer takes 35%, while on single player it takes only 12%.
- Running only one mod which is "Yet Another Boss Health Bar v1.1.3)

**Comment by blushiemagic** [comment]
Fixed by 7458e21ec1861e227b8e7b899297fa72cae73876
