### ISSUE TITLE
Crafting ui very glitchy

### ISSUE THREAD

**Issue by PokeDerg** [blushiemagic/MagicStorage#199]
my friend was having this issue when i was running a steam server, then i got it by hosting the server on "host and play" by myself

what happens is the ui doesnt open, my vanity amor and equipment hides itself and i gain 51 speed if i hold right click over the crafting interface, if my cursor is over where the ui will spawn it will open with no items or recipies shown, here is the error if i try to change the recipie mode
![image](https://user-images.githubusercontent.com/80658697/178436919-7b2c9fab-99f5-4756-b6bc-fd5c7f2efd9a.png)

when it works (I host the server on a console window and my friend then has the issue) it doesnt have the error or do any of this stuff

**Comment by PokeDerg** [comment]
seems to have been a mod incompatibility with this mod

![image](https://user-images.githubusercontent.com/80658697/178439559-84998a32-0d6e-43b4-a9db-6c1901167547.png)

**Comment by ExterminatorX99** [comment]
It might not be a mod incompatibility.
Try going into your tModLoader install folder and deleting the `dotnet` folder
