### ISSUE TITLE
1.4 Version Multiplayer Chunk Ban

### ISSUE THREAD

**Issue by Meowordie** [blushiemagic/MagicStorage#201]
Hey Guys, so I know a ton of people have had this issue before, but that was a long time ago and I appear to be having similar issues to multiple people from Issue #41. I would look into the fixes listed there, but I am running a Windows Server, and it is the 1.4 version. One singular storage heart and container causes the NPCs from the other pylons (not the ones near me) to fall through the world due to what I assume to be those chunks unloading. So rather than unloading the chunk it was in, it is unloading chunks that are near pylons as my spawn base has no pylon near it. Also, after the first time closing the server after putting items in the entire storage system deleted itself from my world and is completely gone. Please help me. :(

**Comment by ExterminatorX99** [comment]
Please replicate the issue and send the relevant server log file

Does this happen with ONLY Magic Storage enabled/loaded?

**Comment by Meowordie** [comment]
I am running only 4 mods
Fargo's Mutant and Souls
Magic Storage
And Recipe Browser

I have run the world with Magic Storage only and my NPCs still drop through the floor.
Even stranger is that despite my NPCS appearing to drop through the floor whenever I haven't loaded that area, when I move towards them nothing is messed up. However, my storage with about 16 storage blocks and only about 600 items max deleted itself from my world.

This [server.log](https://github.com/blushiemagic/MagicStorage/files/9126068/server.log) file should be the one we were playing on for a while, before I reopened the server and the magic storage went missing


![20220716110522_1](https://user-images.githubusercontent.com/17240991/179360650-136dab79-2a6e-443b-9f26-cec468818da8.jpg)
![20220716110433_1](https://user-images.githubusercontent.com/17240991/179360652-5f6146ac-00cc-42ef-9796-5bcd47eb77c6.jpg)
![20220716110517_1](https://user-images.githubusercontent.com/17240991/179360653-94faf81a-fbd8-4590-ac33-af9a2af8b8da.jpg)
.

**Comment by ExterminatorX99** [comment]
Do the npcs fall through the world without any mods loaded? If they do, test if they still fall on preview(also without mods)

**Comment by ExterminatorX99** [comment]
About the entire storage disappearing. 
You're not the first person it happened to, but it seems unrelated to magic storage since ALL modded tiles disappear from the world.

Do you know of any other modded tiles in your world that you can check if they are still there so we can confirm if this is the case?

The only "solution" to it is to restore a backup of the world before the modded tiles got corrupted

**Comment by Meowordie** [comment]
I kept the Mutant Statue from Fargo's Eternity Mode stuff and yeah it's gone.

**Comment by Meowordie** [comment]
How would I go about recovering a backup of the Terraria World?

**Comment by ExterminatorX99** [comment]
`C:\Users\<Username>\Documents\My Games\Terraria\tModLoader\Worlds\Backup`

**Comment by Meowordie** [comment]
Got it. Thank you so much for helping me out even though this wasn't inherently a Magic Storage Issue, I just kinda blamed it as the culprit because it has done things like this in the past to me before they were fixed.
