### ISSUE TITLE
[1.4] Item tooltips in the storage contain GlobalItem debug message

### ISSUE THREAD

**Issue by cc004** [blushiemagic/MagicStorage#202]
There are always tooltips about global item data above the item name text, which is quite annoying. I'm not sure if it is a bug, but I think it shouldn't be there since it is marked as `GlobalItemDebug_` in the source code.
https://github.com/blushiemagic/MagicStorage/blob/6bf7f252721bae5120872a365a3487917d5b43a8/Common/Global/GUITooltips.cs#L44-L46

**Comment by ExterminatorX99** [comment]
There's a config option for it

**Comment by cc004** [comment]
Oh, I've missed it. Thank you
