### ISSUE TITLE
Magic storage issue

### ISSUE THREAD

**Issue by CraftyLizard98** [blushiemagic/MagicStorage#208]
So basically what's happening is it won't let me store anything in it after I place 3 storage boxes and a storage heart all connected and I upgraded them with the Crimtane upgrade I bring up the page to deposite or take things out and it won't let me deposit anything idk if any one else has had this problem but it's really frustrating and would love some answers thank you.

**Comment by absoluteAquarian** [comment]
Known issue.  This is caused by a bug that was introduced in v0.5.7.2  
Deposit items into storage via Shift+Click or the Deposit All button in the meantime.
