### ISSUE TITLE
Lags with RecursiveCraft installed

### ISSUE THREAD

**Issue by DeadMor0z** [blushiemagic/MagicStorage#220]
If RecursiveCraft is installed, then when hovering over any slot (empty or ocuppied) in MagicStorage UI (no matter - storage or crafting) will make game to lag very much. No lags happen if hovering mouse over player inventory slots or any other normal storage slots (empty or occupied).
Looks like some RecursiveCraft function is called every update tick when updating MagicStorage interfaces (why?)
Logs look normal, no errors or warning there.

**Comment by DeadMor0z** [comment]
This fixes the issue:

```diff
@@ -76,7 +76,9 @@ namespace MagicStorage.UI {

                                        // Handle handles all the click and hover actions based on the context.
                                        storedItemBeforeHandle = StoredItem.Clone();
-                                       ItemSlot.Handle(ref storedItem, Context);
+                                       dummy[10] = storedItem;
+                                       ItemSlot.Handle(dummy, Context, 10);
+                                       storedItem = dummy[10];

                                        if (ItemChanged || ItemTypeChanged)
                                                OnItemChanged?.Invoke(storedItem);```

**Comment by absoluteAquarian** [comment]
thanks for reporting this!
