### ISSUE TITLE
Automaton not recogniz(ing/ed by) the Princess in dialogs

### ISSUE THREAD

**Issue by ScoutTheSaneless** [blushiemagic/MagicStorage#225]
Ive recently just gotten the Princess within my save and she throws raw translation data when trying to say something about the Automaton Towny, and same w the Automaton registering the Princess, since she likes all the townies and all the townies like her and have something to say when living near her

**Comment by absoluteAquarian** [comment]
Thanks for reporting this!  Magic Storage is currently missing localization entries for these because I forgot about them.
