### ISSUE TITLE
Stacking not working in the magic storage

### ISSUE THREAD

**Issue by LonguCodes** [blushiemagic/MagicStorage#226]
Version: v0.5.7.10

Stacks of items are not combining in the interface when using deposit all. You have to manually take them out (they will stack in inventory) then put back in

![image](https://user-images.githubusercontent.com/48600606/219117529-3b3847a2-7879-474b-b6d7-4b5083490aee.png)

**Comment by absoluteAquarian** [comment]
Magic Storage is much stricter about whether it will allow item stacks to combine.  The stacks that are not combining have different "item data" on them
