### ISSUE TITLE
"entry point not found" error in crafting interface

### ISSUE THREAD

**Issue by Shadowex3** [blushiemagic/MagicStorage#228]
Not sure what I did to cause this, possibly unloading/reloading mods, but now I can't open the crafting interface at all.
![Screenshot 2023-03-26 17 16 55](https://user-images.githubusercontent.com/57022604/227782012-813fc32d-9174-43ff-ab44-d7fd7f99873f.png)

**Comment by ExterminatorX99** [comment]
Close your game. Go into your your tModLoader installation folder and delete the `dotnet` folder.
Then launch the game normally and the issue should be fixed

**Comment by Shadowex3** [comment]
That fixed it. Was this caused by something I did and should watch out for in the future?

[edit]

Came back immediately after trying to use the environment module and Weapon Enchantments mod. Deleting dotnet fixed it again.

**Comment by ExterminatorX99** [comment]
Weird dotnet issue. No idea what causes it. Nothing that is your or our fault.
