### ISSUE TITLE
When matching recipe to stored ingredients, allow selection of which to use

### ISSUE THREAD

**Issue by slippycheeze** [blushiemagic/MagicStorage#23]
When a recipe has multiple possible sources, the "first" stored ingredient suitable for use is always chosen when using the crafting interface.

For example, to make glass you can use either "sand block" or "hardened sand block".  "sand block" is shown first in the "stored ingredients" section, and is used in crafting.  If it runs out, the crafting switches nicely to the "hardened sand block".

In some cases I might want to use a specific ingredient, since "sand block" can be used to craft "sandstone brick", but "hardened sand block" can't.

It would be nice to be able to select which of the equivalent ingredients were used by clicking on them in the "stored ingredients" display.

**Comment by blushiemagic** [comment]
Resolved by 0f5e96396ecc2ccce5c5af8d82a5b9639ac339ef
