### ISSUE TITLE
Magic Storage destroying left side worlds ocean.

### ISSUE THREAD

**Issue by Shadow558** [blushiemagic/MagicStorage#231]
This has happened 2 times as of writing this so I am playing on singleplayer and sometimes when I login my tmodloader page will make it look like this is my first time logging in, my mods are all there and my characters and worlds are too and I load in to my world and my entire magic storage system is lost with around 300 items sometimes more and my left ocean is just gone all of the wall times are still there but no blocks are spawned and it's just a void all the way to the bottom of my world. Please help.
Edit 1: I normally place down around 30 storage blocks instead of upgrading.
mod list:
Lui Afk Reborn
Fargos soul mod
Ore excavator
Fargos mutant mod
Cheat sheet
Structure helper
Boss checklist
Recipe browser
Calamity Mod Music
Vanilla Calamity Mod Music
Calamity Mod 
Magic storage
Teleport to pylons anywhere
Weapon Out
Subworld library
Calamity interludes
Vitality mod
Helpful npcs
Begone evil
multihitbox npc library
craftable rod of discord
craftable accessories
shorter respawn time
fargos best of both worlds
Alchemist npc lite
auto trash

**Comment by ExterminatorX99** [comment]
All modded tiles in your world have disappeared. We don't know why it happens, or if it's even related to Magic Storage.
Best solution we have for people is to load a backup of their world from before this happened.
Steps for restoring backups are at the start of [this google doc](https://docs.google.com/document/d/1CvyOI5teQpxTbUkIL6xbxfKtFNdnIzAUCjwiV68aUYI/edit?usp=sharing)

**Comment by Shadow558** [comment]
Great thank you for helping.
