### ISSUE TITLE
SeriousCommonLib not detected in mod loader and making it so my storage wont load

### ISSUE THREAD

**Issue by Duckymuckyaaa** [blushiemagic/MagicStorage#255]
Whenever I try to load the mod it says I can't because Serious Common Lib is not detected.

**Comment by ExterminatorX99** [comment]
Install it

**Comment by absoluteAquarian** [comment]
Look at the list of **Required Items** on the [workshop page for Magic Storage](https://steamcommunity.com/sharedfiles/filedetails/?id=2563309347)
