### ISSUE TITLE
Every time I try to craft something for which I do not have enough materials, it does not show how many materials I have available

### ISSUE THREAD

**Issue by olexiitimashov** [blushiemagic/MagicStorage#256]
For example I try to craft chestplate
![image](https://github.com/blushiemagic/MagicStorage/assets/113458059/9c3e7db3-c76a-4019-a648-d3367b5d4e5f)
as you can see on the screen there is no material
although he is
![image](https://github.com/blushiemagic/MagicStorage/assets/113458059/7c30eeb1-e52c-4704-bc87-64a0decb1114)
As you can see from the screenshot, I have 9 Bee Wax 
in theory, I should have shown the amount of Bee Wax when I tried to craft a chestplate

in settings i have -1 recursion depth
when i set it to 0 
then became as it should be
![image](https://github.com/blushiemagic/MagicStorage/assets/113458059/f7d2e2e4-a63b-4ef0-a39c-4c70d98ad005)

**Comment by olexiitimashov** [comment]
![image](https://github.com/blushiemagic/MagicStorage/assets/113458059/8d77b654-6d10-4855-848c-c61bc6a3e1e4)

**Comment by absoluteAquarian** [comment]
Update to v0.6.0.2
