### ISSUE TITLE
Quick stack allows you to dupe items in new version 0.6.0.2

### ISSUE THREAD

**Issue by x-a1r-x** [blushiemagic/MagicStorage#257]
If you play in multiplayer, then quick sort does not work correctly. Items are placed in chests, but are not removed from the inventory.
A bug appeared after updating to version 0.6.0.2.
Terraria v1.4.3.6

**Comment by BartMitTyp** [comment]
Still happening in Terraria 1.4.4.9 , so latest magicstorage version

**Comment by absoluteAquarian** [comment]
This will be fixed in the next update, v0.6.0.3
