### ISSUE TITLE
Quick stack into chests broken for hotbar

### ISSUE THREAD

**Issue by zaylivinglive** [blushiemagic/MagicStorage#258]
This is only on multiplayer, not single player. Quick stack will take items from your hotbar, and when it does it will make the item disappear. It will not appear in inventory or in the chest system. Relogging does not solve this, and neither does a server restart. This bug does not happen for items that are pulled from your inventory and not your hotbar. Will happen regardless of it is a item, weapon, consumable or other. Quick workaround is to favorite all your items on your hotbar, as favorites will still not be pulled. On latest version of magic storage. Was not present in last Magic Storage update. Running the following mods; 
"BossChecklist",
  "CalamityMod",
  "CalamityModMusic",
  "MagicStorage",
  "RecipeBrowser",
  "SerousCommonLib",
  "ThoriumMod",
  "AlchemistNPCLite"

**Comment by absoluteAquarian** [comment]
Update to v0.6.0.2
