### ISSUE TITLE
Random items dupilcating

### ISSUE THREAD

**Issue by Minooo21** [blushiemagic/MagicStorage#259]
![16918749437201387120441345372078](https://github.com/blushiemagic/MagicStorage/assets/142121069/99cd06b6-f250-4a8f-9213-18328689b55d)
Recently I've been getting items that I've not necessarily even had in my magic storage duplicate and it duplicates in specifically stacks of 71 regardless of it being an item that isn't supposed to stack for example I've got 11 stacks of 71 depth metres and 3 stacks of 71 iron short swords appear out of nowhere. I can only remove the one by one which is a huge pain clicking it nearly 800 times for the depth metres.

**Comment by edichau** [comment]
same issue

**Comment by absoluteAquarian** [comment]
You're experiencing the quick stacking netcode bug from v0.6.0.1 that was fixed in v0.6.0.2
Update your Magic Storage install to v0.6.0.2
