### ISSUE TITLE
MagicStore cannot be installed by the current tModLoader

### ISSUE THREAD

**Issue by richelbilderbeek** [blushiemagic/MagicStorage#269]
Dear authors of MagicStorage,

Thanks for one of the favorite mods from me and my girlfriend!

However, today (April 1st 2024) tModLoader cannot install MagicStorage anymore:

![Screenshot from 2024-04-01 20-41-41](https://github.com/blushiemagic/MagicStorage/assets/2098230/7c401444-fdbb-46b4-90ec-50657e63f098)

As you can see in this screenshot, one cannot download the MagicStore mod anymore :-/

Could it be made to work again? Would be awesome! I'd be happy to confirm if it works :-)

Thanks and cheers, Richel Bilderbeek

**Comment by ExterminatorX99** [comment]
That means it should already be downloaded. If it is still missing in the mod list try verifying tml game files.

**Comment by richelbilderbeek** [comment]
Yup, silly me :facepalm: . Sorry @ExterminatorX99 for this :-)
