### ISSUE TITLE
Storage Interface doesn't check for Terraria active focus on clicks

### ISSUE THREAD

**Issue by Serity** [blushiemagic/MagicStorage#29]
If you alt-tab out of Terraria's window, but click your mouse where a UI element of the storage would be (whether it's items, deposit all, or sort, but maybe not the text boxes?), the magic storage picks up on the click despite Terraria not being in focus.

Kind of irritating accidentally clicking "Deposit All" or grabbing items out of storage when Terraria is in the background.

**Comment by SuperCuber** [comment]
Perhaps related, if you click on an npc that is standing in front of storage units it shows the "active x/x" message in addition to opening the npc's window
