### ISSUE TITLE
Incompatible with Kalciphoz's RPG Mod  

### ISSUE THREAD

**Issue by charlestain** [blushiemagic/MagicStorage#35]
sorry to bother you but i have noticed that your mod doesnt work with the rpg mod as when you try to open the storage the menu doesnt show up so i was wondering if by any chance there is a simple fix that i could do or is it more complicated ? thank you.

**Comment by whismerhill** [comment]
#33

**Comment by blushiemagic** [comment]
Duplicate of #33
