### ISSUE TITLE
Expeditions Photos don't play nice with magic storage

### ISSUE THREAD

**Issue by ancientpower** [blushiemagic/MagicStorage#46]
The photos produced by the Expeditions mod seem to react poorly with magic storage and have a multitude of bugs when used in conjunction. To see what I mean, install both mods, take a photo with the expeditions camera, and deposit it in a magic storage unit.

**Comment by blushiemagic** [comment]
That's a bug with the Expeditions mod. For some reason it keeps track of what kind of photo it is by how many items are in the item stack.
