### ISSUE TITLE
Crash after opening magic storage

### ISSUE THREAD

**Issue by NucIeus** [blushiemagic/MagicStorage#61]
![20180820150326_1](https://user-images.githubusercontent.com/42543330/44342422-3ae07c80-a48b-11e8-94b5-09faaa01ce57.jpg)

**Comment by GamerBrenno** [comment]
My friend is experiencing the same problem after the update. I am the one hosting the server and I'm fine whenever I look into the magic storage. He say this is the same message that he gets. If it helps, this is the set-up we have: 
![image](https://user-images.githubusercontent.com/42555168/44365494-00c9a780-a498-11e8-9bef-a1d0456883dc.png)
