### ISSUE TITLE
Closing issue

### ISSUE THREAD

**Issue by Blazer4Hire** [blushiemagic/MagicStorage#78]
I was using this mod for the first time.(Which I love) but every time I use it I have to press escape twice in order to get out of crafting terminal or storage heart. I will do more testing to see what it could be and update if I was just being dumb or something.

**Comment by Blazer4Hire** [comment]
Ok I think I found the problem. I turned off auto pause and I don't have any issues now. So yes it was me being dumb....again....

**Comment by blushiemagic** [comment]
Fixed by 84cabf681b918524e350f79fccc6538b3b404b3b
