### ISSUE TITLE
Suggestion/Question: Mod Support For Crafting Stations

### ISSUE THREAD

**Issue by Tothar** [blushiemagic/MagicStorage#88]
Edit:  It appears that I was incorrect as to it not working to at least some degree. I do see that you have worked cross mod compatibility but to what extent I am unsure. The other day I was specifically testing with the Hephaestus Forge from Ancients Awakened but it seemed to take away some of the recipes I'd had before I'd put it in. I don't know if it was just me being clueless or if that specific crafting station isn't doing all it claims to be capable of.

The mod's amazing, one issue that I've been running into has been with the crafting interface and it's limited slots. Some of the other big mods that I've been using including Ancients Awakened and Fargo's Mod both have crafting stations that count as multiple stations but are included in a single entity. Adding support for these condensed crafting stations or even adding your own condensed stations would be awesome.

Having multiple crafting terminals to switch to when I need a different recipe is definitely a First World problem. Also, I don't know if it's possible with the current design of the mod, but being able to put items in or out of your system while in the crafting screen would be a massive help. Maybe it could open an even wider window with the crafting on the left and the storage on the right.

Again, you've made one of the best mods out there, having a modpack would be basically impossible without yours.

**Comment by blushiemagic** [comment]
If modded condensed crafting stations do not work, it is a problem with that mod.

I've considered putting another storage window on the right, but that runs into problems with lower resolutions; the crafting station already doesn't work at the absolute lowest resolution.
