### ISSUE TITLE
Crafting interface unable to be broken

### ISSUE THREAD

**Issue by RaidOfStorms** [blushiemagic/MagicStorage#89]
i cant seem to break the first storage crafting interface i placed in my world, this only seems to work with the first one i place, and this is an issue in every world i make.

**Comment by reachmasterable** [comment]
Did you make sure there are no crafting stuff in it

**Comment by RaidOfStorms** [comment]
I did not, that worked, thank you

Den tis 24 sep. 2019 01:44reachmasterable <notifications@github.com> skrev:
